export const SET_CATEGORY_DATA = 'SET_CATEGORY_DATA';
export const GET_CATEGORY_DATA = 'GET_CATEGORY_DATA'; 
export const SET_CATEGORY_DETAIL_DATA = 'SET_CATEGORY_DETAIL_DATA';
export const GET_CATEGORY_DETAIL_DATA = 'GET_CATEGORY_DETAIL_DATA'; 
export const UPDATE_CATEGORY_DATA = 'UPDATE_CATEGORY_DATA';
export const DELETE_CATEGORY_DATA = 'DELETE_CATEGORY_DATA';