export const SET_WISHLIST_DATA = 'SET_WISHLIST_DATA';
export const POST_WISHLIST_DATA = 'POST_WISHLIST_DATA';
export const GET_WISHLIST_DATA = 'GET_WISHLIST_DATA';
export const DELETE_WISHLIST_DATA = 'DELETE_WISHLIST_DATA';