export const SET_PROVINCE_DATA = 'SET_PROVINCE_DATA';
export const GET_PROVINCE_DATA = 'GET_PROVINCE_DATA'; 

export const SET_CITY_DATA = 'SET_CITY_DATA';
export const GET_CITY_DATA = 'GET_CITY_DATA'; 

export const SET_SHIPPING_COST_DATA = 'SET_SHIPPING_COST_DATA';
export const GET_SHIPPING_COST_DATA = 'GET_SHIPPING_COST_DATA'; 

export const SET_TRANSACTION_DATA = 'SET_TRANSACTION_DATA';

export const CREATE_TRANSACTION_DATA = 'CREATE_TRANSACTION_DATA';
