export const SET_TRANSACTION_DATA = 'admin/SET_TRANSACTION_DATA';
export const GET_TRANSACTION_DATA = 'admin/GET_TRANSACTION_DATA'; 
export const SET_TRANSACTION_DETAIL_DATA = 'admin/SET_TRANSACTION_DETAIL_DATA';
export const GET_TRANSACTION_DETAIL_DATA = 'admin/GET_TRANSACTION_DETAIL_DATA'; 
export const UPDATE_TRANSACTION_DATA = 'admin/UPDATE_TRANSACTION_DATA';
export const UPDATE_TRANSACTION_ADMIN_DATA = 'admin/UPDATE_TRANSACTION_ADMIN_DATA';
