export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_DATA_DETAIL = 'SET_USER_DATA_DETAIL';
export const GET_USER_DATA = 'GET_USER_DATA'; 
export const GET_DETAIL_USER_DATA = 'GET_DETAIL_USER_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const DELETE_USER_DATA = 'DELETE_USER_DATA';