export const SET_TRANSACTION_DETAIL_DATA = 'SET_TRANSACTION_DETAIL_DATA';
export const GET_TRANSACTION_DETAIL_DATA = 'GET_TRANSACTION_DETAIL_DATA'; 
export const UPDATE_TRANSACTION_DETAIL_DATA = 'UPDATE_TRANSACTION_DETAIL_DATA ';
export const SET_REVIEW_DATA_BY_TR = 'SET_REVIEW_DATA_BY_TR';
export const GET_REVIEW_DATA_BY_TR = 'GET_REVIEW_DATA_BY_TR'; 
export const CREATE_REVIEW_DATA = 'CREATE_REVIEW_DATA';
export const UPDATE_REVIEW_DATA= 'UPDATE_REVIEW_DATA';

